services:
  db:
    image: postgres:16
    container_name: recruitify-db
    environment:
      POSTGRES_DB: recruitify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: recruitify-app
    depends_on:
      - db
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/recruitify_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_SQL_INIT_MODE: always
      SPRING_SQL_INIT_SCHEMA_LOCATIONS: classpath:schema.sql
      APP_PYTHON_MICROSERVICE_URL: http://host.docker.internal:5000/parse
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

volumes:
  db_data:
