spring.application.name=recruitify


spring.r2dbc.url=r2dbc:postgresql://localhost:5432/recruitify_db
spring.r2dbc.username=postgres
spring.r2dbc.password=admin
# Enable automatic schema initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql


# API documentation paths
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html


leadiq.base-url=https://api.leadiq.com/graphql
leadiq.api-key=hm_prod_f5168907634356216644c588f144d191178ed7c86a8b28d8c7e8f6575302961f
leadiq.default-limit=25
leadiq.timeout-seconds=20
