spring.application.name=recruitify


spring.r2dbc.url=r2dbc:postgresql://localhost:5432/recruitify_db
spring.r2dbc.username=postgres
spring.r2dbc.password=S@ndi@0972
# Enable automatic schema initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql


# API documentation paths
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html