spring.application.name=recruitify


spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/recruitify_db}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:postgres}
# spring.r2dbc.url=r2dbc:postgresql://localhost:5432/recruitify_db
# spring.r2dbc.username=postgres
# spring.r2dbc.password=admin
# Enable automatic schema initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Email Configuration
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=c212b6a652b5523cd90c6b7fed427bd1
spring.mail.from=hello@demomailtrap.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application scoring and vacancy closing
app.application.scoring.threshold=0.5
app.vacancy.closing.check-delay-ms=60000


# API documentation paths
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

# CV parsing microservice
app.python.microservice.url=${APP_PYTHON_MICROSERVICE_URL:http://localhost:5000/parse}

# SerpAPI (Google candidate search)
serpapi.api-key=f7121d233b17566aaebd7a9f44f094aabab4bdf20ec423d506c12663ed7e7581
serpapi.default-site=${SERPAPI_DEFAULT_SITE:linkedin.com/in}
serpapi.min-limit=${SERPAPI_MIN_LIMIT:5}
serpapi.default-limit=${SERPAPI_DEFAULT_LIMIT:10}
serpapi.timeout-seconds=${SERPAPI_TIMEOUT_SECONDS:20}

# Snov.io (Email Finder)
snovio.client-id=f2e6e794e6d985fb7ec5f95aec5bd6e2
snovio.client-secret=1f7d2319a7328f0f83d073c2fe416b2f
snovio.default-domain=${SNOVIO_DEFAULT_DOMAIN:}
snovio.timeout-seconds=${SNOVIO_TIMEOUT_SECONDS:20}
